### ISSUE TITLE
Get currently-installed version of module?

### ISSUE THREAD

**Issue by kenahoo** [miyagawa/cpanminus#269]
Is it possible to query `cpanm` for the currently-installed version of something, in addition to showing the version available on CPAN?  This is a handy feature of `CPAN.pm`, and presumably something `cpanm` already knows, but doesn't expose.  It would be a nice addition to the `--info` output if that's not strictly defined (perhaps for programmatic use) to be just the CPAN file path.

Apologies if this has already been debated & rejected, or if it's available already & I've missed it.

**Comment by miyagawa** [comment]
closing for now
