### ISSUE TITLE
Feature request: Enable cpanminus on older perl versions

### ISSUE THREAD

**Issue by crenz** [miyagawa/cpanminus#355]
If cpanminus would be OK to use earlier versions of Module::Build (and possibly other prereqs), getting it to work on older perl versions would be easier. From my point of view, support of 5.8.6 out of the box would be quite desirable, as this is still a rather popular version.

Background: I tried installing cpanminus on my Synology NAS with an ipkg-provided perl 5.10.0 using the recommended method (+ "-k" to get rid of a certificate error):

curl -k -L http://cpanmin.us | perl - App::cpanminus

cpanminus executed fine, but reported Module::Build, ExtUtils::Install as prerequisites. As a result, cpanminus has spent about 1.5 hours updating various modules, finally resulting in these messages:

Successfully installed Module-Build-0.4204 (upgraded from 0.2808_01)
ExtUtils::Install is up to date. (1.54)
Building and testing App-cpanminus-1.7001 ... OK
Successfully installed App-cpanminus-1.7001
20 distributions installed

**Comment by dolmen** [comment]
@crenz `cpanm` does not upgrade your toolchain just for its pleasure. This is to fix toolchain bugs!
