### ISSUE TITLE
--installdeps and configure_requires in cpanfile

### ISSUE THREAD

**Issue by debug-ito** [miyagawa/cpanminus#398]
cpanm version: 1.7004

When I (and travis-ci) run `cpanm --installdeps .` in my git repository, it won't install configure_requires written in cpanfile.

On the other hand, if I generate and put META.json before installdeps, the cpanm installs configure_requires written in META.json.

Shouldn't cpanm install configure_requires in cpanfile when META.json or META.yml is not there? If that's possible, I don't have to maintain META files in my repository.

**Comment by miyagawa** [comment]
Fixed with #482
