### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by nickdesaulniers** [miyagawa/cpanminus#428]
From the directions in the readme:

```
curl -L https://cpanmin.us | perl - --sudo App::cpanminus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by miyagawa** [comment]
SSL v3 is deprecated and your curl must be too old. Try upgrading curl or
use the URL with http instead of https.

**Comment by nickdesaulniers** [comment]
yep, thanks!  For anyone in the future, OSX 10.8.5 has a pretty old version of curl `curl 7.24.0`.  With homebrew it's possible to install newer versions `curl 7.39.0` that use Apple's SecureTransport rather than OpenSSL.

**Comment by Hellgold** [comment]
@Miygawa: How do I upgrade Curl? Tripped over the very same error message displayed today when trying to install cpanminus.

**Comment by miyagawa** [comment]
@Hellgold depends on what OS you're using.
