### ISSUE TITLE
Request --save option

### ISSUE THREAD

**Issue by phillipadsmith** [miyagawa/cpanminus#437]
It would be helpful to have a --save option, similar to how `bower` and `npm` work, i.e., where providing a --save flag indicates that you'd like to install that module and append a line to the cpanfile for that module.

**Comment by miyagawa** [comment]
I think it makes more sense to have it in Carton rather than cpanm.

**Comment by phillipadsmith** [comment]
Ah, yes, you are correct. That is what I was thinking of...

**Comment by phillipadsmith** [comment]
Opened: https://github.com/perl-carton/carton/issues/189   :)
