### ISSUE TITLE
Idea: print work directory when a flag is set

### ISSUE THREAD

**Issue by reneeb** [miyagawa/cpanminus#439]
For some automated tasks, I would need the work directory, but I do not want to use "verbose". I'd like to have a flag that prints the path of the work directory... I can create a pull request when I get a name for that flag (in a "private" version of cpanm I use "print-dir", but that is not a good name ;-) ).

**Comment by reneeb** [comment]
This is what it would look like:

```
$ sudo perl ./cpanm -l mytest --print-dir Mojolicious
Work directory is /home/reneeb/.cpanm/work/1425476167.6993
--> Working on Mojolicious
Fetching http://www.cpan.org/authors/id/S/SR/SRI/Mojolicious-6.01.tar.gz ... 
[...]
$ sudo perl ./cpanm -l mytest Mojolicious
--> Working on Mojolicious
Fetching http://www.cpan.org/authors/id/S/SR/SRI/Mojolicious-6.01.tar.gz ... OK
```

**Comment by miyagawa** [comment]
> For some automated tasks, I would need the work directory

Once you run cpanm you'll get the work directory symbolic linked in `~/.cpanm/latest-build`, if that helps.

**Comment by reneeb** [comment]
That doesn't  help in my case because it might happen that several cpanm instances run in parallel at a time.

**Comment by miyagawa** [comment]
You can then use a unique variable set to PERL_CPANM_HOME for each instance, which will guarantee the uniqueness.

**Comment by reneeb** [comment]
cool, that will work then I guess. Thanks!
