### ISSUE TITLE
cpanm --dev does not find releases by unauthorized authors

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#442]
I'm not entirely sure cpanm is at fault here, but I can't find anything else that could be the culprit...

    $ cpanm --dev ExtUtils::MakeMaker
    --> Working on ExtUtils::MakeMaker
    Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.05_20.tar.gz ... OK
    Configuring ExtUtils-MakeMaker-7.05_20 ... OK
    Building and testing ExtUtils-MakeMaker-7.05_20 ... OK
    Successfully installed ExtUtils-MakeMaker-7.05_20 (upgraded from 7.05_19)
    1 distribution installed

    $ cpanm --dev Time::Piece
    Time::Piece is up to date. (1.29)

...but there is a Time-Piece-1.29_03, uploaded by ESAYM (the indexed releases are by RJBS).
Why can cpanm see the dev releases of EUMM but not Time-Piece?

**Comment by miyagawa** [comment]
I'll try to add some debugging option flag to see what kind of query cpanm is sending to MetaCPAN, since I'm sure it's the problem on their end :)

**Comment by miyagawa** [comment]
cpanm relies on MetaCPAN's indexing flags, where it sees the permission table to see if a devel release is an "authorized" release by the author themselves.

                        { term => { 'module.authorized' => JSON::PP::true() } },
                        { term => { 'module.indexed' => JSON::PP::true() } },
                        { term => { 'module.name' => $args->{package} } },

These flags are always set, even for dev release search.

I can see why you want to override this in a rare occasion, but I think as a default, only allowing the dev release by the authors is a sane behavior.
