### ISSUE TITLE
cpanm hangs indfinitely 

### ISSUE THREAD

**Issue by penguin02007** [miyagawa/cpanminus#443]
In the process of configuring perlbrew and adding few modules. I think somehow cpanm broke, not sure how. Now when I execute cpanm, it just hangs indefinitely. Is there a way I can remove cpanm gracefully and starts from scratch?

$ perl -v
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

$ cpanm -v
cpanm (App::cpanminus) 1.7027 on perl 5.018002 built for darwin-thread-multi-2level
Work directory is /Users/lchan/.cpanm/work/1429116134.1080
You have make /usr/local/bin/make
You have LWP 6.05
[...HANGS]
$ cpanm
[...HANGS]

**Comment by miyagawa** [comment]
try `rm $(which cpanm)`

**Comment by penguin02007** [comment]
No luck. Do a force install and it still hangs.

# tail /var/root/.cpanm/work/1429156861.1535/build.log 
cpanm (App::cpanminus) 1.7027 on perl 5.018002 built for darwin-thread-multi-2level
Work directory is /var/root/.cpanm/work/1429156861.1535
You have make /usr/local/bin/make
You have LWP 6.05

**Comment by miyagawa** [comment]
it seems to be hanging when it tries to locate `tar` command. Try debugging where you have them in your PATH, maybe you have a (really) bad tar.

**Comment by penguin02007** [comment]
That's it! Thank you! How did you find out?

I installed PerlPowerTools and caused it. Removing it now.

$ tar --help
/usr/local/bin/tar version [unknown] calling Getopt::Std::getopts (version 1.07 [paranoid]),
running under Perl version 5.18.2.

Usage: tar [-OPTIONS [-MORE_OPTIONS]] [--] [PROGRAM_ARG1 ...]

The following single-character options are accepted:
	With arguments: -f
	Boolean (without arguments): -c -t -x -v -m -z -Z

Options may be merged together.  -- stops processing of options.
Space is not required between options and their arguments.

For more details run
	perldoc -F /usr/local/bin/tar
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]

**Comment by miyagawa** [comment]
because I had that problem :)
https://github.com/tokuhirom/plenv/issues/78
