### ISSUE TITLE
False assumption about location of .meta directory

### ISSUE THREAD

**Issue by mavit** [miyagawa/cpanminus#457]
I get the following error when I try to run `carton bundle` on Red Hat Enterprise Linux 7:
```
invalid top directory at /usr/share/perl5/File/Find.pm line 464.
```

I see that `Carton::Packer` expects to find at least one `.meta` subdirectory in the directories listed in `@INC`.  On my system it passes an empty list, causing the above exception.

Function `App::cpanminus::script::save_meta` writes to
`$Config{sitelibexp}/$Config{archname}/.meta` (which has value `/usr/local/share/perl5/x86_64-linux-thread-multi/.meta` on my machine).  However, the code itself gets installed to `/usr/local/lib64/perl5` (which is the value of `$Config{sitearchexp}`).

`@INC` contains `/usr/local/lib64/perl5` and `/usr/local/share/perl5`, but not `/usr/local/share/perl5/x86_64-linux-thread-multi`, hence Carton::Packer is unable to find the `.meta` directory.

Maybe this is a problem with `Carton::Packer`; I don't know enough about how this is supposed to work to say for sure.

**Comment by miyagawa** [comment]
Try running the bundle command with --no-fatpack. This will be the default in the next release,
