### ISSUE TITLE
verify not working on Ubuntu

### ISSUE THREAD

**Issue by sapphirecat** [miyagawa/cpanminus#458]
```
$ ~/perl5/bin/cpanm --verify Plack::Middleware::Debug
--> Working on Plack::Middleware::Debug
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Plack-Middleware-Debug-0.16.tar.gz ... OK
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/CHECKSUMS ... OK
gpg: verify signatures failed: eof
! Verifying CHECKSUMS signature failed:
! Failed to fetch distribution Plack-Middleware-Debug-0.16
```

Same results with cpanm 1.7014 from the Ubuntu Vivid repo, cpanm 1.7034 from App::cpanminus (also on Vivid), and 1.7004 from Ubuntu Utopic repo. `gpg --version` reports "gpg (GnuPG) 1.4.18" on Vivid and 1.4.16 on Utopic.

From looking around, it seems the file is fetched OK with the size, md5, and sha256 sums matching what's listed in `MIYAGAWA.CHECKSUMS`. cpanm is just not able to verify them?

It's part of an image build script, and the last known-good run of that script was on 2015-May-11 (building a Utopic image; I'm trying to update the scripts to Vivid now.) I'm not really sure what's relevant to this problem, so if you need more info, please ask.

**Comment by miyagawa** [comment]
This is most likely an issue with the upstream Module::Signature. I saw some updates on the module recently discussing the compatibility with CPAN.pm and cpanm. Check out what version of Module::Signature you have and update to the latest if it's not.
