### ISSUE TITLE
Build log location on Win32 impossible to guess

### ISSUE THREAD

**Issue by dolmen** [miyagawa/cpanminus#459]
On Win32 `cpanm` does not create `~/.cpanm/work/latest` (because `symlink` is [not implemented](http://perldoc.perl.org/perlport.html) on Win32). In 2015 everybody on Win32 uses NTFS on the system drive and NTFS supports symlinks. [Win32::Symlink](https://metacpan.org/pod/Win32::Symlink) could be used as a workaround.

Use case:
> I'm testing [my project](/dolmen/github-keygen/) on Win32 with [AppVeyor.com](https://www.appveyor.com). My install phase use `cpanm` to install dependencies, but [the build fails](https://ci.appveyor.com/project/dolmen/github-keygen/build/1.0.3) and cpanm says to look at `C:\Users\appveyor\.cpanm\work\xxx.yy\build.log`, but there is no way to guess this path to write it in the build script in order to dump the log on stdout in case of build failure.

**Comment by miyagawa** [comment]
But it does copy the file to ~/.cpanm/build.log, doesn't it?

**Comment by miyagawa** [comment]
When there's no symlink, it copies the build.log into ~/.cpanm/build.log so that you can cat the file when the exit code is failure in cpanm.

**Comment by dolmen** [comment]
Yes the file is copied to `%USERPROFILE%\.cpanm\build.log`.

I wrote this workaround before (re-)discovering this feature.
```
cpanm Win32::Symlink
perl -MWin32::Symlink -S cpanm --installdeps --with-develop . || type %USERPROFILE%\.cpanm\latest-build\build.log
```
