### ISSUE TITLE
secondary modules in a distribution are re-installed unnecessarily

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#466]
I'm not quite sure what is going on here, but here are the symptoms:

```
: [ether@bourbon ]$; cpanm Test::Deep::UnorderedPairElements
--> Working on Test::Deep::UnorderedPairElements
Fetching http://mirrors.gossamer-threads.com/CPAN/authors/id/E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz ... OK
Configuring Test-Deep-UnorderedPairs-0.005 ... OK
Building and testing Test-Deep-UnorderedPairs-0.005 ... OK
Successfully installed Test-Deep-UnorderedPairs-0.005
1 distribution installed
: [ether@bourbon ]$; 
: [ether@bourbon ]$; cpanm Test::Deep::UnorderedPairElements
--> Working on Test::Deep::UnorderedPairElements
Fetching http://mirrors.gossamer-threads.com/CPAN/authors/id/E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz ... OK
Configuring Test-Deep-UnorderedPairs-0.005 ... OK
Building and testing Test-Deep-UnorderedPairs-0.005 ... OK
Successfully installed Test-Deep-UnorderedPairs-0.005
1 distribution installed
: [ether@bourbon ]$; 
: [ether@bourbon ]$; cpanm Test::Deep::UnorderedPairElements
--> Working on Test::Deep::UnorderedPairElements
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz ... OK
Configuring Test-Deep-UnorderedPairs-0.005 ... OK
Building and testing Test-Deep-UnorderedPairs-0.005 ... OK
Successfully installed Test-Deep-UnorderedPairs-0.005
1 distribution installed
```

Test::Deep::UnorderedPairElements is an indexed module in Test-Deep-UnorderedPairs:

    Test::Deep::UnorderedPairElements 0.005  E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz
    Test::Deep::UnorderedPairKeys     0.005  E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz
    Test::Deep::UnorderedPairs        0.005  E/ET/ETHER/Test-Deep-UnorderedPairs-0.005.tar.gz

Wouldn't subsequent requests to install it be aborted, just like in:

    : [ether@bourbon ]$; cpanm Test::Deep::UnorderedPairs
    Test::Deep::UnorderedPairs is up to date. (0.005)

This distribution has a 'provides' hash in META.json which looks correct, also.

**Comment by miyagawa** [comment]
This is because Test::Deep::UnorderedPairElements is a submodule that cannot be required directly. cpanm uses Module::Metadata to find the installed information for a given module and compare it with the version in module index.

If you want to be able to depend on such sub-packages, make them a separate .pm files so you can require them. If that's not the case, being able to install them via those names is an accidental feature because PAUSE indexes them.

**Comment by karenetheridge** [comment]
Sorry, I was under the impression that cpanm used its saved .meta file to know what has already been installed (the submodules would be recorded in that), rather than trying to do Module::Metadata->new_from_module($blah).

**Comment by miyagawa** [comment]
> the submodules would be recorded in that

it would be, but then there might be the case where multiple distributions provide the same package (think Alt::) and we don't know which one to prefer. Just using Module::Metadata is the right way to do, at least as of today and in sync with other CPAN clients.

**Comment by karenetheridge** [comment]
> Just using Module::Metadata is the right way to do

Yes, I think that's perfectly reasonable. :)
