### ISSUE TITLE
Irrelevant error when mirror is inaccessible

### ISSUE THREAD

**Issue by Altreus** [miyagawa/cpanminus#469]
If you set up a mirror you can't access, you get an irrelevant error. I've only come across this with a 403 Forbidden so far.

    $ cpanm --mirror http://403.forbidden.com Internal::Module
    ! Finding Internal::Module on cpanmetadb failed.
    ! cannot open file '/root/.cpanm/sources/http%403.forbidden.com/02packages.details.txt.gz': No such file or directory opening compressed index
    ! Couldn't find module or a distribution Internal::Module

**Comment by miyagawa** [comment]
I can't reproduce locally.

```
> cpanm --mirror http://403.forbidden.com Internal::Module 
! Finding Internal::Module on cpanmetadb failed.
! Finding Internal::Module () on mirror http://www.cpan.org failed.
! Finding Internal::Module () on mirror http://403.forbidden.com failed.
! Couldn't find module or a distribution Internal::Module
```

 Do you have LWP installed? If you are using curl or wget as an HTTP client backend cpanm can't get the right status code. In cpanm 2 I will switch to HTTP::Tinyish which can detect HTTP status code out of  these backends as well. But for now you can install LWP to get the full status support.
