### ISSUE TITLE
cpanm doesn't work with BusyBox wget

### ISSUE THREAD

**Issue by stro** [miyagawa/cpanminus#471]
BusyBox provides stripped down utilities (including wget), so typical calls to wget fails because of unrecognized options. It would be nice to have BusyBox support as well, usually these are low-power devices that would benefit from not having full-sized CPAN client (especially with Metadata, as it takes too much memory).

Here's how it looks like:

[root@Yig tmp]# cpanm CPAN::SQLite
/usr/bin/wget: unrecognized option `--user-agent'
BusyBox v1.2.2 (2008.01.18-09:29+0000) multi-call binary

Usage: wget [-c|--continue] [-q|--quiet] [-O|--output-document file]
                [--header 'header: value'] [-Y|--proxy on/off] [-P DIR] url

wget retrieves files via HTTP or FTP

Options:
        -c      continue retrieval of aborted transfers
        -q      quiet mode - do not print
        -P      Set directory prefix to DIR
        -O      save to filename ('-' for stdout)
        -Y      use proxy ('on' or 'off')

! Finding CPAN::SQLite on cpanmetadb failed.
/usr/bin/wget: unrecognized option `--user-agent'
BusyBox v1.2.2 (2008.01.18-09:29+0000) multi-call binary

Usage: wget [-c|--continue] [-q|--quiet] [-O|--output-document file]
                [--header 'header: value'] [-Y|--proxy on/off] [-P DIR] url

wget retrieves files via HTTP or FTP

Options:
        -c      continue retrieval of aborted transfers
        -q      quiet mode - do not print
        -P      Set directory prefix to DIR
        -O      save to filename ('-' for stdout)
        -Y      use proxy ('on' or 'off')

/usr/bin/wget: unrecognized option `--user-agent'
BusyBox v1.2.2 (2008.01.18-09:29+0000) multi-call binary

Usage: wget [-c|--continue] [-q|--quiet] [-O|--output-document file]
                [--header 'header: value'] [-Y|--proxy on/off] [-P DIR] url

wget retrieves files via HTTP or FTP

Options:
        -c      continue retrieval of aborted transfers
        -q      quiet mode - do not print
        -P      Set directory prefix to DIR
        -O      save to filename ('-' for stdout)
        -Y      use proxy ('on' or 'off')

! Finding CPAN::SQLite () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution CPAN::SQLite

**Comment by miyagawa** [comment]
This is fixed in a 2.0 branch by making sure all options are available in wget, and for the current version you can disable wget with `--no-wget` to use the embedded HTTP::Tiny client.

**Comment by jimonreal** [comment]
@miyagawa I have the same issue on cpanminus 1.7040
`cpanm (App::cpanminus) version 1.7040 (/usr/local/bin/cpanm)`

When trying the `--no-wget` option I get the following

```
cpanm Module::Install --no-wget
! Finding Module::Install on cpanmetadb failed.
! Finding Module::Install () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Module::Install
```

Is there some workaround?

**Comment by miyagawa** [comment]
You enable the verbose logging with `--verbose` or look at the `~/.cpanm/build.log` for more details. it's likely you're using the curl version or LWP if it's installed, and you can disable them all with `--no-curl` and `--no-lwp` as well.

**Comment by jimonreal** [comment]
@miyagawa I get the same output with the last 2 flags you posted.

This is the build.log file:
```
cpanm (App::cpanminus) 1.7040 on perl 5.022001 built for i686-linux-thread-multi
Work directory is /root/.cpanm/work/1455136102.309
You have make /usr/bin/make
Falling back to HTTP::Tiny 0.056
You have /bin/tar:
You have /usr/bin/unzip
Searching Module::Install () on cpanmetadb ...
-> FAIL Finding Module::Install on cpanmetadb failed.
Searching Module::Install () on metacpan ...
! Could not find a release matching Module::Install () on MetaCPAN.
Searching Module::Install on mirror http://www.cpan.org ...
Downloading index file http://www.cpan.org/modules/02packages.details.txt.gz ...
-> FAIL Finding Module::Install () on mirror http://www.cpan.org failed.
-> FAIL Couldn't find module or a distribution Module::Install

```

**Comment by miyagawa** [comment]
It looks like your box cannot access either cpanmetadb, metacpan or www.cpan.org through port 80.

**Comment by jimonreal** [comment]
I had a problem to do so in the `cpan>` environment. I had to change the `urllist` to a local server in my country `http://cpan.dcc.uchile.cl/`
Is there a way to do the same on cpanminus?

**Comment by miyagawa** [comment]
use `-M` option. use `--help` to see more options.

**Comment by jimonreal** [comment]
Thanks! that worked :)
