### ISSUE TITLE
cpanm does not register all installed modules in perllocal.pod

### ISSUE THREAD

**Issue by hakonhagland** [miyagawa/cpanminus#474]
According to [CPAN Frequently Asked Questions](http://www.cpan.org/misc/cpan-faq.html):

```
Each time a module is installed on your system, 
it appends information to a file called `perllocal.pod`
```

I have installed several CPAN modules using `cpanm`, the problem is that some modules do not get registered in `perllocal.pod`. For example, I have installed `String::Escape`, `String::ShellQuote`, and `String::Util` using `cpanm`. If I type

```
$ perldoc -u perllocal | grep String::
```

I get output:

```
=head2 Tue Apr 21 16:47:34 2015: C<Module> L<String::Escape|String::Escape>
=head2 Thu Aug  6 18:51:04 2015: C<Module> L<String::ShellQuote|String::ShellQuote>
```

Note that `String::Util` is missing, even if all three modules are installed under directory `/home/hakon/perl5/lib/perl5/`. For example, if I type:

```
$ perldoc -l String::Util
```

I get output:

```
/home/hakon/perl5/lib/perl5/String/Util.pod
```

Note: this question was first asked at stackoverflow.com. The link is [here](http://stackoverflow.com/questions/32679413/cpanm-does-not-register-all-installed-modules-in-perllocal-pod)

**Comment by miyagawa** [comment]
It is not cpanm (or any CPAN installer) which does the registration. Build tools (MakeMaker, Module::Build) do the process upon `make install`.

**Comment by miyagawa** [comment]
Module::Build does not add entries to perllocal.pod: http://rt.cpan.org/Ticket/Display.html?id=14316
