### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by gregoa** [miyagawa/cpanminus#480]
In Debian we are currently applying the following patch to
App-cpanminus.
We thought you might be interested in it too.

    Description: fix a spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-01-04
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/cpanminus.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by miyagawa** [comment]
Thanks. Just out of curiosity, is there any reason you didn't go patch upstream (here) first? Doesn't sound like an urgent or debian-speciic bug to patch local first.

**Comment by gregoa** [comment]
On Mon, 04 Jan 2016 10:58:23 -0800, Tatsuhiko Miyagawa wrote:

> Thanks. Just out of curiosity, is there any reason you didn't go
> patch upstream (here) first? Doesn't sound like an urgent or
> debian-speciic bug to patch local first.

Thanks for applying the patch!

I was about the upload the latest release to Debian, when I (well:
lintian) found the typo, and when I create a patch anyway I can just
as well apply it to our package. -- So it's more "both at the same
time" and pure convenience or habit. And laziness, since we have
tooling to forward patches :)

Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Little Richard: Groovie Little Suzi

**Comment by miyagawa** [comment]
Hmm, ok. If you have a tooling, consider actually submitting a pull request rather than linking to a patch? It would make life a lot easier since it's just hitting the Merge button :)

**Comment by gregoa** [comment]
On Mon, 04 Jan 2016 11:38:54 -0800, Tatsuhiko Miyagawa wrote:

> Hmm, ok. If you have a tooling, consider actually submitting a pull
> request rather than linking to a patch? It would make life a lot
> easier since it's just hitting the Merge button :)

Ack, this has already come to my mind before.
I've now added an item in pkg-perl-tool's TODO file for it.


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Bettina Wegner: Andre, die das Land so sehr nicht liebten
