### ISSUE TITLE
installation crashes if build.log symlink points to not existing file

### ISSUE THREAD

**Issue by ruz** [miyagawa/cpanminus#483]
Hi,

We use latest cpanm (deploy script just installs fresh version) and recently (month or so) our deploys started to crash. Looks like actual build log is removed by cpanm, but ~/.cpanm/build.log symlink is still there, in such situations cpanm crashes.

**Comment by miyagawa** [comment]
I can't reproduce.

```
➜  ~  rm ~/.cpanm/build.log                  
➜  ~  ln -s /tmp/foobar.log ~/.cpanm/build.log
➜  ~  ll ~/.cpanm/build.log                   
lrwxr-xr-x  1 miyagawa  staff    15B Jan 14 08:47 /Users/miyagawa/.cpanm/build.log -> /tmp/foobar.log
➜  ~  cpanm DBI
DBI is up to date. (1.634)
```

If you can reproduce reliably, please reopen the ticket with your OS, perl version, cpanm version and the actual error log ("it crashes" could mean very different things).

**Comment by miyagawa** [comment]
I've seen a possibly similar issue when you run cpanm with root (sudo) and then run it with the non-root account and see a permission error. If that's the case, there's nothing you can do about it in cpanm and deleting the log file will make it work again.
