### ISSUE TITLE
uninstall (-U) does not find modules installed in paths from upgraded point releases of perl

### ISSUE THREAD

**Issue by y** [miyagawa/cpanminus#485]
I had originally installed perl 5.22.0 with perlbrew and then upgraded to 5.22.1, so my `@INC` now includes 5.22.0 and 5.22.1, i.e.

    $ perl -E 'say for @INC'
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1/darwin-2level
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1
    /Users/y/perlbrew/perls/perl-5.22/lib/5.22.1/darwin-2level
    /Users/y/perlbrew/perls/perl-5.22/lib/5.22.1
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl

But cpanm is only looking in 5.22.1 for modules and not looking in 5.22.0:

    $ cpanm -v -U IO::AIO
    cpanm (App::cpanminus) 1.7027 on perl 5.022001 built for darwin-2level
    Work directory is /Users/y/.cpanm/work/1453216800.44159
    You have make /usr/bin/make
    You have LWP 6.15
    You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
    You have /usr/bin/unzip
    ! IO::AIO is not found in the following directories and can't be uninstalled.

    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1/darwin-2level
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1

    $ cpan-outdated --verbose
    IO::AIO                        4.32    4.33    M/ML/MLEHMANN/IO-AIO-4.33.tar.gz

    $ find /Users/y/perlbrew/perls/perl-5.22/ | grep IO/AIO
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level/auto/IO/AIO
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level/auto/IO/AIO/.packlist
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level/auto/IO/AIO/AIO.bundle
    /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level/IO/AIO.pm

**Comment by miyagawa** [comment]
can you paste the output of `perl -V`?

**Comment by y** [comment]
$ perl -V

    Summary of my perl5 (revision 5 version 22 subversion 1) configuration:
    
    Platform:
        osname=darwin, osvers=15.2.0, archname=darwin-2level
        uname='darwin y.local 15.2.0 darwin kernel version 15.2.0: fri nov 13 19:56:56 pst 2015; root:xnu-3248.20.55~2release_x86_64 x86_64 '
        config_args='-de -Dprefix=/Users/y/perlbrew/perls/perl-5.22 -Aeval:scriptdir=/Users/y/perlbrew/perls/perl-5.22/bin'
        hint=recommended, useposix=true, d_sigaction=define
        useithreads=undef, usemultiplicity=undef
        use64bitint=define, use64bitall=define, uselongdouble=undef
        usemymalloc=n, bincompat5005=undef
    Compiler:
        cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include',
        optimize='-O3',
        cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include'
        ccversion='', gccversion='4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)', gccosandvers=''
        intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
        d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
        ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
        alignbytes=8, prototype=define
    Linker and Libraries:
        ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector-strong -L/usr/local/lib -L/opt/local/lib'
        libpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /opt/local/lib
        libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
        perllibs=-lpthread -ldl -lm -lutil -lc
        libc=, so=dylib, useshrplib=false, libperl=libperl.a
        gnulibc_version=''
    Dynamic Linking:
        dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
        cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong'


    Characteristics of this binary (from libperl): 
    Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                            PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
                            PERL_NEW_COPY_ON_WRITE PERL_PRESERVE_IVUV
                            USE_64_BIT_ALL USE_64_BIT_INT USE_LARGE_FILES
                            USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                            USE_LOCALE_NUMERIC USE_LOCALE_TIME USE_PERLIO
                            USE_PERL_ATOF
    Built under darwin
    Compiled at Dec 13 2015 22:34:15
    %ENV:
        PERLBREW_BASHRC_VERSION="0.73"
        PERLBREW_HOME="/Users/y/.perlbrew"
        PERLBREW_MANPATH="/Users/y/perlbrew/perls/perl-5.22/man"
        PERLBREW_PATH="/Users/y/perlbrew/bin:/Users/y/perlbrew/perls/perl-5.22/bin"
        PERLBREW_PERL="perl-5.22"
        PERLBREW_ROOT="/Users/y/perlbrew"
        PERLBREW_VERSION="0.73"
        PERL_CPANM_OPT="-q"
    @INC:
        /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1/darwin-2level
        /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.1
        /Users/y/perlbrew/perls/perl-5.22/lib/5.22.1/darwin-2level
        /Users/y/perlbrew/perls/perl-5.22/lib/5.22.1
        /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0/darwin-2level
        /Users/y/perlbrew/perls/perl-5.22/lib/site_perl/5.22.0
        /Users/y/perlbrew/perls/perl-5.22/lib/site_perl
        .

**Comment by miyagawa** [comment]
cpanm searches for `installsitearch` and `installsitelib` by default to uninstall modules from. The include paths you inherit from previous perl minor releases are excluded from the search path.

I consider this as a known behavior rather than extending search paths which would definitely confuses the existing users.

**Comment by y** [comment]
Well, at least App::pmuninstall will properly find and delete those modules...

**Comment by miyagawa** [comment]
I'd say that's not a correct behavior since you're removing a file that other versions of perl might still depend on. But if that's what you want, continue using pmuninstall.
