### ISSUE TITLE
--installdeps . and --with-xxx options

### ISSUE THREAD

**Issue by zdm** [miyagawa/cpanminus#486]
Hi.
Is it possible to use --with-... options together with --installdeps?
For example, I need to install all deps with the feature "linux". I run the following command:

```
cpanm --with-feature linux --with-recommends --with-suggests --installdeps .
```

current cpanfile is:

```
requires 'Pcore::GeoIP';
```

Pcore::GeoIP has the following cpanfile (and META.json, generated from this cpanfile):

```
requires 'Pcore';
requires 'Geo::IP::PurePerl';
requires 'Geo::IP';
requires 'GeoIP2';
feature linux => sub {
    recommends 'MaxMind::DB::Reader::XS';
};
```

I expect, that cpanm will try to install 'MaxMind::DB::Reader::XS'. But I don't see any activity, related to the 'MaxMind::DB::Reader::XS' installation.

**Comment by miyagawa** [comment]
`--with-feature` only applies to modules specified in the command line arguments, but not dependencies. The reasoning for that is that what `linux` feature means is different from one dist to another.

**Comment by zdm** [comment]
And what about --with-suggests, --with-recommends options?
They are also don;t work in this case?

**Comment by miyagawa** [comment]
`--with-suggests` and `--dev` will work with dependencies.

`--configure-args` etc. are only for command line arguments, as well.

**Comment by zdm** [comment]
This is not so rare case, when some dependency is mandatory under, for example, Linux, but not mandatory, or, even, not exists, under MSWin?

Is it possible to solve this with current cpanm functionality?

**Comment by miyagawa** [comment]
I understand that this is sometimes required, especially when combined with tools like carton or carmel. I have a plan to solve this in carton/carmel to override the build options per dists.

Currently you can just run `cpanm --with-feature linux Pcore::GeoIP` *before* running `cpanm --installdeps .`

**Comment by zdm** [comment]
Thank you.
This will work, and I will use this.
But it is not handy, to write and support this additional commands in all Dockerfiles for all projects.

Thank you again.
