### ISSUE TITLE
attempt to install "latest" module results in installing perl

### ISSUE THREAD

**Issue by djerius** [miyagawa/cpanminus#487]
% cpanm --version
    cpanm (App::cpanminus) version 1.7040 ([...]/perl-5.22/bin/cpanm)
    perl version 5.022001 ([...]/perl-5.22/bin/perl)

      %Config:
	archname=x86_64-linux_CentOS-6-thread-multi
	installsitelib=[...]/perl-5.22/lib/site_perl/5.22.1
	installsitebin=[...]/perl-5.22/bin
	installman1dir=[...]/perl-5.22/man/man1
	installman3dir=[...]/perl-5.22/man/man3
	sitearchexp=[...]/perl-5.22/lib/site_perl/5.22.1/x86_64-linux_CentOS-6-thread-multi
	sitelibexp=[...]/perl-5.22/lib/site_perl/5.22.1
	archlibexp=[...]/perl-5.22/lib/5.22.1/x86_64-linux_CentOS-6-thread-multi
	privlibexp=[...]/perl-5.22/lib/5.22.1
      %ENV:
      @INC:
	FatPacked::33445728=HASH(0x1fe5760)
	[...]/perl-5.22/lib/site_perl/5.22.1/x86_64-linux_CentOS-6-thread-multi
	[...]/perl-5.22/lib/site_perl/5.22.1
	[...]/perl-5.22/lib/5.22.1/x86_64-linux_CentOS-6-thread-multi
	[...]/perl-5.22/lib/5.22.1
	/proj/axaf/simul/lib/perl5
	/proj/axaf/simul/x86_64-linux_CentOS-6/lib/perl5/x86_64-linux_CentOS-6-thread-multi
	/proj/axaf/simul/x86_64-linux_CentOS-6/lib/perl5
	.

    % cpans -l 1 latest
    latest - Use the latest Perl features
    [Limit 1 reached, use -l to change limit]

    % cpanm latest
    --> Working on latest
    Fetching file:///proj/axaf/ots/import/perl/perl-5.22.1.tar.gz ... OK

While

	% cpan latest
	CPAN: Storable loaded ok (v2.53_01)
	Reading '/home/dj/tmp/cpan/Metadata'
	  Database was generated on Wed, 10 Feb 2016 16:17:02 GMT
	CPAN: Module::CoreList loaded ok (v5.20151213)
	latest is up to date (0.03).

**Comment by skaji** [comment]
I couldn't reproduce it.
```
> cpanm latest
--> Working on latest
Fetching http://www.cpan.org/authors/id/A/AN/ANDYA/latest-0.03.tar.gz ... OK
Configuring latest-0.03 ... OK
Building and testing latest-0.03 ... OK
Successfully installed latest-0.03
1 distribution installed
```
I suspect you set some cpan mirrors (via PERL_CPANM_OPT).
`Fetching file:///proj/axaf/ots/import/perl/perl-5.22.1.tar.gz ... OK` is weird.

Also check `~/.cpanm/build.log` or try `cpanm --verbose latest` agiain.

**Comment by miyagawa** [comment]
Yep you seem to have a custom mirror that has `latest` mapped to the perl-5.22.1. See what you have with `PERL_CPANM_OPT` and see if the mirror has the wrong mapping.

**Comment by djerius** [comment]
Well this is embarrassing.   I had a symbolic link named "latest" linked to the Perl tarball in the current directory.  Ooops.

My apologies for the noise.
