### ISSUE TITLE
Resolve name not parsing Github uris

### ISSUE THREAD

**Issue by pjfl** [miyagawa/cpanminus#488]
This works

   cpanm git://github.com/pjfl/p5-app-doh.git

but Github displays and copies to clipboard either of

   git@github.com:pjfl/p5-app-doh.git
   https://github.com/pjfl/p5-app-doh.git

neither of which works.  I suppose I could try persuading Github to add a third option but....

**Comment by miyagawa** [comment]
They both work for me.
