### ISSUE TITLE
Recursive git dependencies support

### ISSUE THREAD

**Issue by kak-tus** [miyagawa/cpanminus#489]
Hello,

I've added some PR's near three years ago about support of github/private git repositories as dependencies in cpanfiles.
They were discarded, but:
- no changes in cpanminus in this direction (while, another users want same functionality, as I see in issues/PR's);
- we've used it in production for three years to build packages;
- and, at last, it is not very conveniently to support or install or use another forked version of cpanminus.

May be, it is a good idea to put this code in cpanminus master?

What we have:
1. Support for git/private git repositories in format

```
requires 'protocol://...URI...';
```
1. Support of recursive clone of same git dependencies in dependent cpanfiles (--installalldepsfromlocalcpanfiles option). May be, it is little long name...
2. Support of speedup clone repositories to specified path (--clone-path option). It clones repository if it is not exists, or just pull it.

Also, we have more specific options:
4. Support for globally set checkouted branch via --git-branch option. It checkout specified branch, if it exists or checkout master branch. It used in case, when developer want to test build with fixes in multiplie repositories.
5. Support for automated merge specified branch in some premaster branch to test build in preproduction.

4 and 5 options may be not usefull for another users, but I will be happy to see 1-3 in master, and, i think, same as community.

**Comment by alambike** [comment]
:+1: sounds good, what is the fork?

**Comment by kak-tus** [comment]
It is in a private repository, but I will publish it in a little time.

**Comment by kak-tus** [comment]
I've published it as PR's.

**Comment by kak-tus** [comment]
I don't use cpanm anymore and think - it's time to close this issue.
