### ISSUE TITLE
ExtUtils::Manifest not found error on CentOS 7

### ISSUE THREAD

**Issue by alvesjmp** [miyagawa/cpanminus#493]
I have just tried running cpanm to install some modules, and came across a potential problem (or error on my part?).

Command:
sudo ./cpanm --install CGI::Pretty

Results in:

```
Fetching http://www.cpan.org/authors/id/L/LE/.../CGI-4.28.tar.gz OK
Configuring CGI-4.28... N/A
Can't locate ExtUtils/Manifest.pm in @INC (...) at ./cpan line 132.
```

This also happens for other modules I tried to install. Any help would be greatly appreciated.

The system is a freshly installed CentOS 7 desktop.

**Comment by miyagawa** [comment]
I don't know why your error trace says  `at ./cpan line 132` - `cpan` is a program provided by CPAN.pm and has nothing to do with cpanm.

Anyway, I think you need to install p5 base modules (perl-core) for CentOS or Fedora because they strip out core modules from p5 and that causes a lot of problems like this.

**Comment by alvesjmp** [comment]
Oops, sorry, I accidentally removed the 'm' there. It is cpanm that should be written there.

**Comment by miyagawa** [comment]
Can you try installing perl-core rpm?

**Comment by alvesjmp** [comment]
After installing perl-core (yum install perl-core), which indeed contains ExtUtils::Manifest, then the problem disappeared, so I am closing the issue. Thanks for your help!

**Comment by aero** [comment]
I frequently encounter this problem.
RHEL/CentOS  default perl installation doesn't include all perl core modules but perl-core package does.
Ubuntu default perl-base installation doesn't include all perl core modules but perl package does..

Is is possible to bundle missing core module in cpanm ?
or internally detect linux distro, perl packages during the cpanm installation
and print a guide how to set up sane perl environment like the following.

RHEL/CentOS
yum install perl-core
yum groupinstall 'Development Tools'

Ubuntu/Debian
apt-get install perl
apt-get install build-essential
