### ISSUE TITLE
feature request: log to build.log even in --verbose mode

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#494]
Even if installing in --verbose mode, it is sitll helpful to have the full build output in build.log, e.g. for tools such as App-cpanminus-reporter. Would it be possible?

**Comment by karenetheridge** [comment]
cc @garu

**Comment by miyagawa** [comment]
Dupe of #253 

I tried once and it wasn't as easy as I wished.

**Comment by miyagawa** [comment]
Also #350 :)
