### ISSUE TITLE
Current install method is vulnerable to MitM

### ISSUE THREAD

**Issue by elgalu** [miyagawa/cpanminus#505]
IMHO the current install method seems vulnerable to MitM (man-in-the-middle attack) see for example the step:

```sh
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz ... OK
```

Fetching from a non secured endpoint (no HTTPS at http://www.cpan.org) is unsafe unless a secure hash check like SHA-256 is included right after fetching the file.

**Comment by miyagawa** [comment]
we have the following options:

- `-M https://metacpan.cpan.org/` (or whatever https mirrors)
- `--verify` - verify CHECKSUMS and SIGNATURES

these are not enabled by default because it requires extra dependencies.

**Comment by elgalu** [comment]
Got `unable to resolve host address ‘metacpan.cpan.org’` and couldn't find any **https** listed mirror however after trying to guess around I found one without certificate errors: https://mirror.checkdomain.de/CPAN/

yay! thanks

**Comment by miyagawa** [comment]
sorry it is `https://cpan.metacpan.org/`
