### ISSUE TITLE
Behaving weirdly on Ubuntu 14 LTS on AWS

### ISSUE THREAD

**Issue by davehodg** [miyagawa/cpanminus#510]
Really odd one. Did my usual perlbrew/cpanm install OK.

Installed DBI.

perl -mDBI failed.

It appears that the path DBI is installed on isn't on the brewed perl's path.

I've stood up Amazon's RHEL derivative and it's fine.

**Comment by miyagawa** [comment]
cpanm runs `perl` command in whatever in your path, and installs to the path configured with that perl. I'm sure when you ran cpanm, your perlbrew setup was incomplete.

**Comment by davehodg** [comment]
As far as I can tell, perlbrew was fine. But your call!

**Comment by miyagawa** [comment]
I can't tell because you didn't provide any logs :)

**Comment by davehodg** [comment]
True. Instance was blown away and replaced by the Amazon RHEL variant pretty quickly. I'm distro-agnostic :)
