### ISSUE TITLE
installdeps fails when mirror-only is specified, even though module is available

### ISSUE THREAD

**Issue by oneandoneis2** [miyagawa/cpanminus#514]
Test case:
cpanfile with just the contents:
`requires 'Regexp::Common', '==2016020301';
`
Try to install the deps:
```
cpanm --installdeps --mirror http://cpan.metacpan.org --local-lib local --mirror-only --cascade-search .
--> Working on .
Configuring /home/djh/tmp ... OK
==> Found dependencies: Regexp::Common
! Finding Regexp::Common (== 2016020301) on mirror http://cpan.metacpan.org failed.
! Couldn't find module or a distribution Regexp::Common (== 2016020301)
! Installing the dependencies failed: Module 'Regexp::Common' is not installed
! Bailing out the installation for ..
```

Exact same command without mirror-only specified:
```
cpanm --installdeps --mirror http://cpan.metacpan.org --local-lib local .                         --> Working on .
Configuring /home/djh/tmp ... OK
==> Found dependencies: Regexp::Common
--> Working on Regexp::Common
Fetching http://cpan.metacpan.org/authors/id/A/AB/ABIGAIL/Regexp-Common-2016020301.tar.gz ... OK
Configuring Regexp-Common-2016020301 ... OK
Building and testing Regexp-Common-2016020301 ...
```

So it can install that module, from the mirror, but not if "mirror only" is in play. Same problem with other mirrors, including backpan.

So far only seems to be an issue when the version number has no point in it - i.e. x.xx works whilst xxx doesn't

**Comment by miyagawa** [comment]
mirror-only only uses `02packages.details.txt.gz`, aka the PAUSE index, which does not have an ability to lookup non-current version of a module.

**Comment by miyagawa** [comment]
> So far only seems to be an issue when the version number has no point in it - i.e. x.xx works whilst xxx doesn't

I don't think that's the case, try with '== 2016060801' which is the current version of the module.
