### ISSUE TITLE
Piping contents of cpanfile doesn't work

### ISSUE THREAD

**Issue by cmahnke** [miyagawa/cpanminus#515]
I try to get a cpanfile via curl and pipe it into cpanminus like this:
curl -s https://raw.githubusercontent.com/subugoe/LibreCat/dev/cpanfile |cpanm -nq --installdeps --cpanfile=- --skip-installed 

This works for the first entries, then fails. What am I missing?

**Comment by miyagawa** [comment]
That is not supported. It's just trying to parse the content of cpanfile as a standard argument.

**Comment by cmahnke** [comment]
Is there a possible workaround like calling via Perl?
Can this be considered as a feature request?

**Comment by miyagawa** [comment]
you should save it to a temp file. This will conflict with the existing feature to read the list of modules from STDIN.
