### ISSUE TITLE
Doesn't install on system without ExtUtils::MakeMaker

### ISSUE THREAD

**Issue by Mekk** [miyagawa/cpanminus#534]
Unfortunately on RH7/centos7 it is possible to install perl without ExtUtils::MakeMaker (which is in separate perl-ExtUtils-MakeMaker. package). And there we get:

```
$ curl -L https://cpanmin.us | perl - App::cpanminus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  298k  100  298k    0     0   592k      0 --:--:-- --:--:-- --:--:--  591k
!
! Can't write to /usr/local/share/perl5 and /usr/local/bin: Installing modules to /home/users/marcink/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl5 and /usr/local/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7043.tar.gz ... OK
==> Found dependencies: ExtUtils::MakeMaker
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.24.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.24 ... OK
Can't locate ExtUtils/Manifest.pm in @INC (@INC contains: FatPacked::22129544=HASH(0x151ab88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at - line 132.
```

So mayhaps you could fatpack MakeMaker too?

(note: I am to use local::lib but to install it I must install cpanm first…)

**Comment by Mekk** [comment]
(or maybe that's matter of some missing dep on ExtUtils::Manifest?  This also is not installed, again, rh7/centos7 keeps it as separate perl-ExtUtils-Manifest package)

**Comment by miyagawa** [comment]
cpanm doesn't work on a perl without core libs installed. Try install whatever rpm package that brings them to your Fedora/RHEL.

**Comment by Mekk** [comment]
If I had root…  

cpanm + local::lib provide nice solution to the problem of user-level installation o truncated perl. The latter  seems to be especially popular on RH/Centos, where distro cuts perl into myriad of packages, and admins „tighten” their machines by installing as little as possible. It used to work for me but, as here, even it sometimes fails.

If you could consider fatpacking a bit more (not necessarily to the default installer, maybe to some cpanmin.us/forstrippedperl), it would be great. I suppose that's mostly a matter of ExtUtils, with them the rest is installable…

( Here is what perl package on centos7 contains: https://pastebin.com/SvtZNTUt , the rest is in separate packages and sometimes is installed, and sometimes is not )

**Comment by snoopyjc** [comment]
I have this same issue.  I'm using git bash on Windows.  Can't get past this in order to install the real package I want!
