### ISSUE TITLE
set PERL_USE_UNSAFE_INC=0 from distribution metadata

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#535]
following up from https://github.com/miyagawa/cpanminus/pull/521, and as per decisions made at the toolchain summit -- $ENV{PERL_USE_UNSAFE_INC} should be set to 0 if `x_use_unsafe_inc => 0` is seen in distribution metadata.

cc @toddr

**Comment by karenetheridge** [comment]
The same request for CPANPLUS (including the git diff): https://rt.cpan.org/Ticket/Display.html?id=121656

The same request for CPAN.pm: https://rt.cpan.org/Ticket/Display.html?id=121659

**Comment by karenetheridge** [comment]
ping! @miyagawa, would you prefer someone take a stab at a patch, or do you want it left with you?

**Comment by toddr** [comment]
I think this is the proposed fix already though it has a typo @haarg https://github.com/miyagawa/cpanminus/pull/536

**Comment by karenetheridge** [comment]
re #536, cool! that was easier than I thought :)

**Comment by miyagawa** [comment]
resolved in 15c8292
