### ISSUE TITLE
Old backpan versions cannot be installed anymore (MetaCPAN API changes?)

### ISSUE THREAD

**Issue by eserte** [miyagawa/cpanminus#538]
Trying to fetch old backpan versions (versions which are not indexed at cpanmetadb) does not work since some days:
```
$ cpanm --look 'DBD::XBase~==0.234' --local-lib=~/perl5
! Finding DBD::XBase (==0.234) on cpanmetadb failed.
Found DBD::XBase 1.08 which doesn't satisfy ==0.234.
```
If it helps, here's the probably relevant strace snippet for the MetaCPAN API request:
```
18929 23:12:46.088079 write(4, "GET /v0/file/_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22query%22%3A%7B%22nested%22%3A%7B%22score_mode%22%3A%22max%22%2C%22query%22%3A%7B%22custom_score%22%3A%7B%22query%22%3A%7B%22constant_score%22%3A%7B%22filter%22%3A%7B%22and%22%3A%5B%7B%22term%22%3A%7B%22module.authorized%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.indexed%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.name%22%3A%22DBD%3A%3AXBase%22%7D%7D%2C%7B%22term%22%3A%7B%22module.version%22%3A%221.01%22%7D%7D%5D%7D%7D%7D%2C%22metacpan_script%22%3A%22score_version_numified%22%7D%7D%2C%22path%22%3A%22module%22%7D%7D%7D%7D%2C%22fields%22%3A%5B%22date%22%2C%22release%22%2C%22author%22%2C%22module%22%2C%22status%22%5D%7D HTTP/1.1\r\nTE: deflate,gzip;q=0.3\r\nConnection: TE, close\r\nHost: api.metacpan.org\r\nUser-Agent: cpanminus/1.7043 perl/5.024001\r\n\r\n", 829) = 829 <0.000027>
```
... and the response:
```
HTTP/1.1 200 OK\r
Server: nginx\r
Content-Type: application/json; charset=utf-8\r
Transfer-Encoding: chunked\r
Accept-Ranges: bytes\r
Date: Thu, 18 May 2017 21:12:46 GMT\r
Via: 1.1 varnish\r
Age: 0\r
Connection: close\r
X-Served-By: cache-fra1235-FRA\r
X-Cache: MISS\r
X-Cache-Hits: 0\r
X-Timer: S1495141966.115772,VS0,VE459\r
Vary: Accept-Encoding\r
\r
20d\r
{
   "hits" : {
      "hits" : []
   },
   "x_metacpan_shim" : {
      "info" : "metacpan-api-v0-shim v0.001 - Only supports cpanm 1.7.  See https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md for updated API documentation, and the /download_url/ end point for download information",
      "query" : {
         "dev" : 1,
         "module" : "DBD::XBase",
         "version" : "== 1.01"
      },
      "query_url" : "https://fastapi.metacpan.org/v1/download_url/DBD::XBase?version=%3D%3D+1.01&dev=1"
   }
}
\r
0\r
\r
```

**Comment by mark-5** [comment]
I think this is the same problem I am seeing in https://github.com/metacpan/metacpan-api/issues/657. I wonder if this is related to any of the metacpan shim changes in the https://github.com/miyagawa/cpanminus/issues/533 discussion.

**Comment by haarg** [comment]
The shim is handling this properly, but the download_url endpoint doesn't seem to be.

**Comment by mark-5** [comment]
@haarg is it possible this was broken in https://github.com/metacpan/metacpan-api-v0-shim/commit/1c2e799c335aaf146b4f1d81986ebf1b5c22df07?

I did a bisect using https://gist.github.com/mark-5/8b3f6aa4429438d40d3ec7a0ffeb9ba7 and it breaks on https://github.com/metacpan/metacpan-api-v0-shim/commit/1c2e799c335aaf146b4f1d81986ebf1b5c22df07

**Comment by haarg** [comment]
This should be fixed now.

**Comment by mark-5** [comment]
Thanks @haarg! This looks to be working from my perspective - the problematic queries are all working successfully now.

The only oddity I noticed is that the [metacpan-api-v0-shim/t/shim.t](https://github.com/metacpan/metacpan-api-v0-shim/blob/master/t/shim.t) test now fails. I'm not sure if that's serious, but it appears to be caused by https://github.com/metacpan/metacpan-api-v0-shim/commit/1b4454e1b9f6b74cc78a5acceea67482edd4aaec.

**Comment by haarg** [comment]
I've fixed the shim to work against all possible variants of cpanm, fixed and expanded the tests, and added a script that will run an arbitrary cpanm against the local shim without needing to run a server (or at least enough for the --info option).  If there are any further problems with cpanm when it is using metacpan, please [report them against the shim](https://github.com/metacpan/metacpan-api-v0-shim/issues).

**Comment by eserte** [comment]
Closing issue.
