### ISSUE TITLE
Cannot clone: error: object d8b2f43020a74999ee26636fbb17fe1d5100e8e7:contains zero-padded file modes

### ISSUE THREAD

**Issue by perlancar** [miyagawa/cpanminus#544]
(This issue should probably be a support request to Github instead.)

Anyone having difficulty cloning this repo? I'm getting:

    $ git clone git@github.com:miyagawa/cpanminus.git
    Cloning into 'cpanminus'...
    remote: Counting objects: 11002, done.
    error: object d8b2f43020a74999ee26636fbb17fe1d5100e8e7:contains zero-padded file modes
    fatal: Error in object
    fatal: index-pack failed

**Comment by skaji** [comment]
I suspect you set `transfer.fsckObjects=true`.
So try `git clone --config transfer.fsckObjects=false git@github.com:miyagawa/cpanminus.git`

**Comment by perlancar** [comment]
Thanks, Shoichi!
