### ISSUE TITLE
menlo fails to extract archives if the path of tar command contains spaces

### ISSUE THREAD

**Issue by skaji** [miyagawa/cpanminus#545]
Since https://github.com/miyagawa/cpanminus/commit/a651c56, menlo uses`File::Which::which()`, not its own `which()`.
So if the path of tar/gzip/bz2/unzip has spaces, menlo fails to extract archives.
I found this in [appveyor](https://ci.appveyor.com/project/skaji/cpm/build/1.0.9).

Do you have any plan to restore the feature of quoting paths of commands,
or replace `system $string`, `qx/$string/` by some safe expressions?

**Comment by miyagawa** [comment]
Adding `shell_quote` like before would be a quick fix for this.
