### ISSUE TITLE
What is number of the current stable release?

### ISSUE THREAD

**Issue by chdiza** [miyagawa/cpanminus#569]
I `git pulled` today, only to discover that `cpanm --version` gives me 1.9009.  Yesterday it was 1.7XXX.  But looking through the commit log (of the devel branch, which is the default branch when one clones from this github repo), the version number jumps back and forth between 1.9X and 1.7X.

Which one is the current stable release?  And why does it keep flip-flopping?

**Comment by miyagawa** [comment]
Don't use `git pull` when you need a stable release, period.

**Comment by miyagawa** [comment]
1.7 is for cpanm, and 1.9 is for Menlo, the backend releases. As a user you will only be interested in cpanm, and the App-cpanminus distribution on CPAN.

**Comment by chdiza** [comment]
> Don't use git pull when you need a stable release, period.

I don't.  I use it to see when cpanminus is changing.  Then I go to the releases tab of the github page and grab the latest.  But that page contains 1.7X and 1.9X intermingled, with no indication of which one is the stable one.  Now I know: thanks!

> 1.7 is for cpanm, and 1.9 is for Menlo, the backend releases. As a user you will only be interested in cpanm, and the App-cpanminus distribution on CPAN.

This should be somewhere on the README (unless it is already there and I somehow missed it).

**Comment by miyagawa** [comment]
I don't think this belongs to README, since as a user you won't see it. I updated the directory structure and also tag names, so that it's clearer which version belongs to which now. Thanks for sharing your concern.

**Comment by chdiza** [comment]
But a visitor to the github site will see the README.

Separately, I think there's been a packaging error.  I dowloaded the tarball for 1.7902 from the releases page.  Then I unzipped it and ran `./cpanm --version`.  It showed me 1.9009.

**Comment by chdiza** [comment]
The same occurs with the tarball for 1.7901.

**Comment by chdiza** [comment]
It is also true of the tarball `cpanminus-App-cpanminus-1.7903.tar.gz`

**Comment by miyagawa** [comment]
You're not supposed to use that download feature and it's not supported. 

I keep `cpanm` file in the root just because some people hotlink to github raw download URL and i can't do anything about it.

The official tarballs on CPAN are the only files that are supported.

**Comment by miyagawa** [comment]
i updated README and removed `cpanm` repo from the root for now (i keep it in `master` branch where it's hotlinked) in 3d8d0fdee96159a43419a06fff27a2e173dd7244

**Comment by chdiza** [comment]
> The official tarballs on CPAN are the only files that are supported.

That tarball, if I run `bin/cpanm --version`, results in `perl: bad interpreter: No such file or directory`.  It's shebang is `#!perl`.

**Comment by miyagawa** [comment]
Yes, that _is_ supported and I advertised in my documentation all the time. I don't understand why your trying to do what is not documented and complaining despite my efforts to recommend staying away.

**Comment by shadowcat-mst** [comment]
$ curl -L https://cpanmin.us | perl - -l$HOME/perl5 App::cpanminus local::lib
    $ echo $(perl -Iperl5/lib/perl -Mlocal::lib) >>.bashrc

**Comment by Grinnz** [comment]
CPAN tarballs can only be used by installing them generally, which you must do either with the configure and build steps mentioned, or by using an installer (like cpanm). cpanminus has a special fatpacked script at https://cpanmin.us which can be used without installing; this is an exception to the rule.

**Comment by miyagawa** [comment]
on 1.9015, i updated the two distros having the same number, since that makes things easier to diagnose.
