### ISSUE TITLE
cpanm not respecting version spec

### ISSUE THREAD

**Issue by djjudas21** [miyagawa/cpanminus#582]
After a running into [a bug with `DBD::mysql` 4.047](https://github.com/perl5-dbi/DBD-mysql/issues/263) I needed to pin to an older version.

Relevant snippet from my `cpanfile`:

```
requires 'DBD::mysql', '4.046';
```

Output from `cpanm`:

```
cpanm --verbose --installdeps --notest .
...
Searching DBD::mysql (4.046) on cpanmetadb ...
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/C/CA/CAPTTOFU/DBD-mysql-4.047.tar.gz ... OK
Unpacking DBD-mysql-4.047.tar.gz
DBD-mysql-4.047/
...
```

Why does it correctly specify 4.046 and then go on to fetch 4.047 anyway?

Full output from Jenkins CI available [here](https://travis-ci.org/djjudas21/photography-database/builds/427632561)

**Comment by miyagawa** [comment]
You have to use `'== 4.046'` to do what you mean.

`'4.046'` means "at a minimum 4.046" per CPAN::Meta::Spec:
https://metacpan.org/pod/CPAN::Meta::Spec#Version-Ranges
