### ISSUE TITLE
Feature request: recognize full metacpan urls

### ISSUE THREAD

**Issue by torbjorn** [miyagawa/cpanminus#586]
Would it be a horrible thing if this just worked:

    cpanm https://metacpan.org/pod/App::cpanminus # to do the same as cpanm App::cpanminus

Saves you the trouble of picking up the mouse to go select and copy that module name on the page and then alt-tab back to the terminal, paste and run

**Comment by miyagawa** [comment]
This is too arbitrary a request to put into cpanm, and can be easily implemented as a shell function or a wrapper.
