### ISSUE TITLE
--mirror-only, --mirror clarifcation

### ISSUE THREAD

**Issue by rlauer6** [miyagawa/cpanminus#594]
Hi, I've read the various threads and documentation and empirically seemed to have grokked how these options work together...

`cpanm --mirror-only --mirror  file:///tmp/DarkPAN --mirror http://www.cpan.org  -i Amazon::API -L local`

So, given the command above it appears to me the the `--mirror-only` option seems to take the next `--mirror` value as the index to search, however by adding additional `--mirror` options _cpanm_ will additionally search those repositories if it fails to find the module in the repository _/tmp/DarkPAN_?

Can you clarify how these options actually work? Only the DarkPAN index is "downloaded" but somehow _cpanm_ is still searching alternate mirrors?  __This is the desired behavior, btw, so I'm glad it works!__ I'm just trying to understand the options since I'm confused by the documentation.

Thanks and thanks for a very useful tool!

**Comment by miyagawa** [comment]
`--mirror-only` controls whether cpanm queries the module against (cpanmetadb)[http://cpanmetadb.plackperl.org/] first, before using the CPAN mirror indexes specified with `--mirror` options.

So yes, if you run that command it will search for the modules from `/tmp/DarkPAN` and also `http://www.cpan.org`.
