### ISSUE TITLE
Running `dzil build` on master for App-cpanminus fails

### ISSUE THREAD

**Issue by kentfredric** [miyagawa/cpanminus#610]
I haven't really been able to understand what I'm seeing here. I understand that generally contributors aren't expected to use dzil for this, but my objective here is to understand the build workflow for cpanm "as it happens for authors".

However, I'm currently blocked by this:
```

dzil build
[Run::BeforeBuild] executing: /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/bin/perl5.27.9 maint/build.pl
[Run::BeforeBuild] Generating cpanm from script/cpanm.PL
[Run::BeforeBuild] executing: /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/bin/perl5.27.9 maint/copy_bin.pl
[Run::BeforeBuild] Generating bin/cpanm from cpanm
[DZ] beginning to build App-cpanminus
[DZ] guessing dist's main_module is lib/App/cpanminus.pm
[@Milla/LicenseFromModule] guessing from lib/App/cpanminus.pm, License is Software::License::Perl_5
[@Milla/LicenseFromModule] Copyright 2010- - Tatsuhiko Miyagawa
[@Milla/Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[@Milla/Git::Contributors] Warning: distribution has non-ascii characters in contributor names. META.json will be unparsable on perls <= 5.8.6 when JSON::PP is lower than 2.27300
[@Milla/StaticInstall] setting x_static_install to 0
[DZ] writing App-cpanminus in App-cpanminus-1.7907
[@Milla/CopyFilesFromBuild] Copied App-cpanminus-1.7907/META.json to META.json
[@Milla/CopyFilesFromBuild] Copied App-cpanminus-1.7907/LICENSE to LICENSE
[@Milla/CopyFilesFromBuild] Copied App-cpanminus-1.7907/Makefile.PL to Makefile.PL
[@Milla/ReadmeAnyFromPod] overriding README.md in root
[Run::AfterBuild] executing: /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/bin/perl5.27.9 -i -nlpe 's{(use ExtUtils::MakeMaker.*)}{"$1\n\n" . qx(cat maint/copy_bin.pl)}e' Makefile.PL
[Run::AfterBuild] executing: /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/bin/perl5.27.9 maint/bump_fatpack.pl 1.7907
[Run::AfterBuild] Died at maint/bump_fatpack.pl line 17.
[Run::AfterBuild] command exited with status 255 (65280)
[Run::AfterBuild] command exited with status 255 (65280) at inline delegation in Dist::Zilla::Plugin::Run::AfterBuild for logger->log_fatal (attribute declared in /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/lib/site_perl/5.27.9/Dist/Zilla/Role/Plugin.pm at line 59) line 18.
```

The cause appears to be that `maint/bump_fatpack.pl` is reading "App-cpanminus/cpanm", seeing none of the expected version declarations, and undef, which trips the "die" on line 17.

I can't tell if this is due to:
- Finding the wrong cpanm
- Finding the right cpanm, but it not having the right content due to some build ordering issue
- If I'm supposed to nuke that file before running `dzil build`
- Or if something else is going on here.

Thanks.

**Comment by kentfredric** [comment]
Hmm, I might be able to answer my own question here. Turns out I didn't have App::FatPacker and Perl::Strip installed, as even though I *thought* I ran authordeps --missing, I somehow missed those.

With them installed, it works properly, its just odd how it didn't fail earlier or louder with them missing.

> [Run::BeforeBuild] executing: /home/kent/perl5/perlbrew/perls/5.27.9-nossp-oaath-nopmc-nodot/bin/perl5.27.9 maint/build.pl

That's all! .. O.o

**Comment by miyagawa** [comment]
That's probably because there's no error check running `fatpack` from build.pl. Let me know if you need any changes there. Closing this ticket for now.
