### ISSUE TITLE
Error install Module Menlo::CLI::Compa

### ISSUE THREAD

**Issue by lucas1** [miyagawa/cpanminus#613]
See error:
[root@162ca593a75b /]# cpanm Menlo::CLI::Compa
! Finding Menlo::CLI::Compa on cpanmetadb failed.
! Finding Menlo::CLI::Compa () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Menlo::CLI::Compa
[root@162ca593a75b /]# cpan Menlo::CLI::Compa
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 24 Jun 2020 21:29:02 GMT
Warning: Cannot install Menlo::CLI::Compa, don't know what it is.
Try the command

    i /Menlo::CLI::Compa/

to find objects with matching identifiers.

had this error when I tried to install Carton:

Successfully installed Path-Tiny-0.114
! Installing the dependencies failed: Module 'Menlo::CLI::Compat' is not installed
! Bailing out the installation for Carton-v1.0.34.
41 distributions installed

I solved installing Menlo::Legacy

**Comment by miyagawa** [comment]
the name of the module is `Menlo::CLI::Compat` (missing "t")
