### ISSUE TITLE
[feature request] autobundle support

### ISSUE THREAD

**Issue by c-alpha** [miyagawa/cpanminus#615]
`autobundle` is your friend when you want to upgrade `perl` itself, and have lots of modules installed. As I'm using `local::lib`, too, I can just go in, axe everything in my perl library dir, and reinstall all modules under the new `perl` from the `autobundle`.

As it seems, `cpanminus` has gained the ability to install bundles hosted on CPAN already with the fix for issue #81. Thus, adding the ability to reinstall everything listed in a local bundle file might not be too cumbersome, perhaps?

Now, the usefulness of the whole scheme depends on keeping the `autobundle` file up to date, which is a manual job up to now. Enter `cpanminus`. If `cpanminus` could do a `perl -MCPAN -eautobundle` (or equivalents thereof) after it has installed or removed one or more modules, that would be pure awesome, because it could make many folks' lives much easier:

1. `cpanm My::Module` (updates autobundle)
1. upgrade `perl` to the next version
1. `rm -rf ~/lib/perl/lib/perl5/*` (or wherever you keep your local module installs)
1. `cpanm Bundle::Snapshot_Latest` (or similar)

**Comment by miyagawa** [comment]
I usually recommend tools like https://metacpan.org/release/App-MigrateModules  or `plenv list-modules` to get the list of modules, then pipe it into `cpanm` in the newer version of modules.

**Comment by c-alpha** [comment]
Good point about `perl-migrate-modules` and `plenv`. My use-case is slightly different, though. I install, and update `perl` through a package manager (homebrew in my case). Hence, after upgrading, the old `perl` executable is no longer available, and the now available, new `perl` more often than not barfs at the modules installed with the previous `perl` version.

That said, `plenv migrate-modules` would not seem applicable, since it appears to require both `perl`s to be installed & working? (And I'll always have a single `perl` version installed only.)

`perl-migrate-modules` could seem workable, as its documentation doesn't seem to suggest that the old `perl` would still need to be available. As I understand the docs, it would require me to devise a new `local::lib` location for each new `perl` version though?

The easy way out for me would be to write a wrapper script around `cpanm`, which updates the autobundle file after having invoked `cpanm`. Then, with some experimenting, I might find a way to get `cpanm` to use a local bundle file for installing instead of getting it from CPAN. I just thought it would be a nice convenience having these functionalities nicely integrated into `cpanm`, for folks like me who install `perl` through a package manager and just always want/need the latest `perl` only.

**Comment by c-alpha** [comment]
Giving it some more thought, I think I'll give `perl-migrate-modules` a try when the next `perl` update comes around, and come back here if `perl-migrate-modules` doesn't cut it.

**Comment by miyagawa** [comment]
The implementation of `plenv list-modules` is as simple as: 
```
perl -MExtUtils::Installed -e 'print "$_$/" for grep $_ ne "Perl", ExtUtils::Installed->new(skip_cwd => 1)->modules'
```

you can just put that into a perl script and then invoke after every time you run cpanm.
