### ISSUE TITLE
Socks5/http proxy support of cpanminus for installation of cpan modules.

### ISSUE THREAD

**Issue by hongyi-zhao** [miyagawa/cpanminus#621]
On Ubuntu 20.10, I try to some modules listed [here](https://metacpan.org/recent) with cpanminus as shown below.

`$ cpanm -l ~/.local/perl/ Zing`

At the same time, I use the following proxy setting for cpan:

```
$ grep -i http_proxy .local/share/.cpan/CPAN/MyConfig.pm
  'http_proxy' => q[http://127.0.0.1:8080],
```
But, it seems the proxy hasn't been used at all.

Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by miyagawa** [comment]
`CPAN/MyConfig.pm` is a configuration for CPAN.pm client, not cpanm.

You can set it to the environment variable like `http_proxy` for cpanm to recognize it, but the actual name of the environment variable differs depending on which HTTP client backend you're using. https://stackoverflow.com/questions/53563834/how-can-cpanm-retrieve-settings-for-a-proxy-that-requires-username-and-password

**Comment by hongyi-zhao** [comment]
I want to know whether I can write it into conf file instead of passing from environment variable.

**Comment by miyagawa** [comment]
cpanm has no configuration file and all the options are configured via command line or environment variables. You can easily write a shell alias, or write a wrapper script in you bin directory to preserve your default configuration.
