### ISSUE TITLE
cpanm needs to glob() arguments on Windows

### ISSUE THREAD

**Issue by DrHyde** [miyagawa/cpanminus#657]
In the CI for one of my modules I needed to use cpanm to install from a tarball on Windows, where I don't know what the tarball is called. On a sane OS, you do that with `cpanm *.tar.gz` and ... job done.

But on Windows that gives [errors](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/4129582384/jobs/7135519218):

```
! Finding *.tar.gz on cpanmetadb failed.
! Finding *.tar.gz () on metacpan failed.
! Finding *.tar.gz () on mirror http://www.cpan.org/ failed.
! Couldn't find module or a distribution *.tar.gz
```

My solution was to run `perl -e "exec(q{cpanm}, map { glob($_) } @ARGV)" *.tar.gz` instead, but I think it would be best if cpanm were to do the globbing itself if running on Windows.

**Comment by miyagawa** [comment]
I think you should use a real shell. adding features like this to cpanm is an unnecessary scope creep.
