### ISSUE TITLE
Found AnyEvent::HTTP::LWP::UserAgent 0.10 which doesn't satisfy 0.8.

### ISSUE THREAD

**Issue by atoomic** [miyagawa/cpanminus#672]
Noticed that issue while running CI 
https://github.com/miyagawa/cpanminus/actions/runs/8846389462/job/24292171782

```
# ==> Found dependencies: AnyEvent::HTTP::LWP::UserAgent
# Searching AnyEvent::HTTP::LWP::UserAgent (0.8) on cpanmetadb ...
# Found AnyEvent::HTTP::LWP::UserAgent 0.10 which doesn't satisfy 0.8.
# -> FAIL Installing the dependencies failed: Module 'AnyEvent::HTTP::LWP::UserAgent' is not installed
# -> FAIL Bailing out the installation for Facebook-Graph-1.0500.
# '
#     doesn't match '(?-xism:Installed version \(0\.10\) of AnyEvent::HTTP::LWP::UserAgent is not in range '0\.8')'
# Looks like you failed 2 tests of 3.
```

**Comment by miyagawa** [comment]
That message "Found AnyEvent::HTTP::LWP::UserAgetn 0.10" is fine - it's expected to be there. It is red herring for when the error message is different when it fails to install the module, rather than detecting a conflicting version.

**Comment by miyagawa** [comment]
I disabled the test on 5.8. Otherwise this isn't an issue.
